language: java
os: linux
dist: xenial

jdk:
  - openjdk8

git:
  clone: false

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

install:
  - git clone --depth=50 --branch=${TRAVIS_BRANCH} https://${GITHUB_TOKEN}@github.com/daichi-m/notification4J.git daichi-m/notification4J.git
  - cd daichi-m/notification4J.git
  - mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

jobs:
  include:

    # Snapshot Build
    - stage: snapshot
      if: NOT(branch == main AND commit_message = "Perform release")
      name: "Build and Deploy Snapshot"
      script:
        - echo "JAVA_HOME=${JAVA_HOME}"
        - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
        - echo "TRAVIS_COMMIT=${TRAVIS_COMMIT}"
        - echo "TRAVIS_COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}"
        - echo "TRAVIS_JOB_NAME=${TRAVIS_JOB_NAME}"
        - echo "TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}"
        - mvn --settings .maven.xml clean deploy -Prelease


     # Release Build
    - stage: release
      if: branch == main AND commit_message = "Perform release"
      name: "Release"
      script:
        - echo "JAVA_HOME=${JAVA_HOME}"
        - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
        - echo "TRAVIS_COMMIT=${TRAVIS_COMMIT}"
        - echo "TRAVIS_COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}"
        - echo "TRAVIS_JOB_NAME=${TRAVIS_JOB_NAME}"
        - echo "TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}"
        - mvn --settings .maven.xml release:prepare release:perform  -B
#        - mvn --settings .maven.xml release:perform -B

after_script:
  - bash <(curl -s https://codecov.io/bash)