language: java
os: linux
dist: xenial

jdk:
  - openjdk8

before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust


install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: environment
      name: "Build ENV"
      script:
        - echo "JAVA_HOME=${JAVA_HOME}"
        - echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
        - echo "TRAVIS_COMMIT=${TRAVIS_COMMIT}"
        - echo "TRAVIS_COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}"
        - echo "TRAVIS_JOB_NAME=${TRAVIS_JOB_NAME}"
        - echo "TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}"
    - stage: snapshot
      name: "Build and Deploy Snapshot"
      script: mvn clean deploy --settings .maven.xml -Prelease
    - stage: release
      if: branch == main AND commit_message = "Perform release"
      name: "Release"
      script: mvn --settings .maven.xml nexus-staging:release


after_script:
  - bash <(curl -s https://codecov.io/bash)